---
codecov:
  notify:
  after_n_builds: 1
coverage:
  range: "25...100"
  status:
   
    project:
      default:
        target: auto
        threshold: "0.05%"
    patch: true
    
    changes: true
