version: '3'
services:
  zookeeper:
    image: zookeeper
    deploy:
      replicas: 3
    ports: 
     - "2181:2181" 
     - "2888:2888" 
     - "3888:3888"
  mesos-master:
    image: mesosphere/mesos-master:1.3.0
    ports:
     - "5050:5050"
     - "5051:5051"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '1'
          memory: 200M
  mesos-agent:
     image: mesosphere/mesos-slave:1.3.0
     replicas: 3
     environment: 
       - MESOS_HOSTNAME=192.168.100.10
       - MESOS_MASTER=zk://zookeeper:2181/mesos 
     
  marathon:
      image: mesosphere/marathon:v1.3.0
      environment:
        - MARATHON_MASTER: zk://127.0.0.1:2181/mesos
      depends_on:
        - zookeeper
